
# ILCSoft version
set( ILCSOFT_PACKAGE_VERSION "v02-00-02" CACHE STRING "The ILCSoft version" )
ilcsoft_set_package_version( PACKAGE ILCSoft                  VERSION ${ILCSOFT_PACKAGE_VERSION} )

# Packages with no install support
ilcsoft_set_package_version( PACKAGE Boost                    VERSION "1.59.0" )
ilcsoft_set_package_version( PACKAGE MySQL                    VERSION "5.1.0" )
ilcsoft_set_package_version( PACKAGE Eigen                    VERSION "3.2.9" )

# ILCSoft base packages versions
ilcsoft_set_package_version( PACKAGE Geant4                   VERSION "v10.3.2" )
ilcsoft_set_package_version( PACKAGE CLHEP                    VERSION "CLHEP_2_3_4_3" )
ilcsoft_set_package_version( PACKAGE ROOT                     VERSION "v6-08-06" )
ilcsoft_set_package_version( PACKAGE GSL                      VERSION "2.1" )
ilcsoft_set_package_version( PACKAGE QT                       VERSION "v4.7.4" )
ilcsoft_set_package_version( PACKAGE CED                      VERSION "v01-09-02" )
ilcsoft_set_package_version( PACKAGE CondDBMySQL              VERSION "CondDBMySQL_ILC-0-9-6" )
ilcsoft_set_package_version( PACKAGE ILCUTIL                  VERSION "v01-05" )
ilcsoft_set_package_version( PACKAGE FastJet                  VERSION "3.2.1" )
ilcsoft_set_package_version( PACKAGE FastJetcontrib           VERSION "1.025" )
ilcsoft_set_package_version( PACKAGE XercesC                  VERSION "Xerces-C_3_2_2" )

# ILCSoft packages versions
ilcsoft_set_package_version( PACKAGE GEAR                     VERSION "v01-08" )
ilcsoft_set_package_version( PACKAGE LCIO                     VERSION "v02-12-01" )
ilcsoft_set_package_version( PACKAGE MarlinFastJet            VERSION "v00-05-01" )
ilcsoft_set_package_version( PACKAGE KalTest                  VERSION "v02-05" )
ilcsoft_set_package_version( PACKAGE KalDet                   VERSION "v01-14-01" )
ilcsoft_set_package_version( PACKAGE aidaTT                   VERSION "v00-09" )
ilcsoft_set_package_version( PACKAGE DDKalTest                VERSION "v01-05" )
ilcsoft_set_package_version( PACKAGE MarlinTrk                VERSION "v02-07" )
ilcsoft_set_package_version( PACKAGE MarlinTrkProcessors      VERSION "v02-10" )
ilcsoft_set_package_version( PACKAGE Clupatra                 VERSION "v01-03" )
ilcsoft_set_package_version( PACKAGE KiTrack                  VERSION "v01-09" )
ilcsoft_set_package_version( PACKAGE KiTrackMarlin            VERSION "v01-12" )
ilcsoft_set_package_version( PACKAGE FCalClusterer            VERSION "v01-00" )
ilcsoft_set_package_version( PACKAGE ForwardTracking          VERSION "v01-13" )
ilcsoft_set_package_version( PACKAGE ConformalTracking        VERSION "v01-07" )
ilcsoft_set_package_version( PACKAGE LICH                     VERSION "v00-01" )
ilcsoft_set_package_version( PACKAGE GBL                      VERSION "V02-01-01" )
ilcsoft_set_package_version( PACKAGE LCCD                     VERSION "v01-05" )
ilcsoft_set_package_version( PACKAGE RAIDA                    VERSION "v01-09" )
ilcsoft_set_package_version( PACKAGE MarlinUtil               VERSION "v01-15" )
ilcsoft_set_package_version( PACKAGE Marlin                   VERSION "v01-16" )
ilcsoft_set_package_version( PACKAGE MarlinDD4hep             VERSION "v00-06" )
ilcsoft_set_package_version( PACKAGE DDMarlinPandora          VERSION "v00-10" )
ilcsoft_set_package_version( PACKAGE MarlinReco               VERSION "v01-25" )
ilcsoft_set_package_version( PACKAGE ILDPerformance           VERSION "v01-06" )
ilcsoft_set_package_version( PACKAGE ILDConfig                VERSION ${ILCSOFT_PACKAGE_VERSION} )
ilcsoft_set_package_version( PACKAGE LCFIVertex               VERSION "v00-07-04" )
ilcsoft_set_package_version( PACKAGE LCFIPlus                 VERSION "v00-07" )
ilcsoft_set_package_version( PACKAGE MarlinKinfit             VERSION "v00-06" )
ilcsoft_set_package_version( PACKAGE MarlinKinfitProcessors   VERSION "v00-04" )
ilcsoft_set_package_version( PACKAGE PandoraPFANew            VERSION "v03-09-00" )
ilcsoft_set_package_version( PACKAGE PandoraAnalysis          VERSION "v02-00-00" )
ilcsoft_set_package_version( PACKAGE CEDViewer                VERSION "v01-16" )
ilcsoft_set_package_version( PACKAGE Overlay                  VERSION "v00-21" )
ilcsoft_set_package_version( PACKAGE PathFinder               VERSION "v00-06-01" )
ilcsoft_set_package_version( PACKAGE MarlinTPC                VERSION "v01-04" )
ilcsoft_set_package_version( PACKAGE LCTuple                  VERSION "v01-11" )
ilcsoft_set_package_version( PACKAGE BBQ                      VERSION "v00-01-03" )
ilcsoft_set_package_version( PACKAGE Garlic                   VERSION "v03-01" )
ilcsoft_set_package_version( PACKAGE DD4hep                   VERSION "v01-07-02" )
ilcsoft_set_package_version( PACKAGE DD4hepExamples           VERSION "v01-07-02" )
ilcsoft_set_package_version( PACKAGE lcgeo                    VERSION "v00-16-03" )
ilcsoft_set_package_version( PACKAGE Physsim                  VERSION "v00-04-01" )
