
set( ILCSOFT_PACKAGE_VERSION "master" CACHE STRING "The ILCSoft version" )
ilcsoft_set_package_version( PACKAGE ILCSoft                  VERSION "master" )

# Packages with no install support
ilcsoft_set_package_version( PACKAGE Boost                    VERSION "1.58.0" )
ilcsoft_set_package_version( PACKAGE MySQL                    VERSION "5.1.0" )
ilcsoft_set_package_version( PACKAGE Eigen                    VERSION "3.2.9" )

# ILCSoft base packages versions
ilcsoft_set_package_version( PACKAGE Geant4                   VERSION "v10.3.2" )
ilcsoft_set_package_version( PACKAGE CLHEP                    VERSION "CLHEP_2_3_4_3" )
ilcsoft_set_package_version( PACKAGE ROOT                     VERSION "v6-08-06" )
ilcsoft_set_package_version( PACKAGE GSL                      VERSION "2.1" )
ilcsoft_set_package_version( PACKAGE QT                       VERSION "v4.7.4" )
ilcsoft_set_package_version( PACKAGE CED                      VERSION "v01-09-02" )
ilcsoft_set_package_version( PACKAGE CondDBMySQL              VERSION "CondDBMySQL_ILC-0-9-6" )
ilcsoft_set_package_version( PACKAGE ILCUTIL                  VERSION "v01-05" )
ilcsoft_set_package_version( PACKAGE FastJet                  VERSION "3.2.1" )
ilcsoft_set_package_version( PACKAGE FastJetcontrib           VERSION "1.025" )
ilcsoft_set_package_version( PACKAGE XercesC                  VERSION "Xerces-C_3_2_2" )

# ILCSoft packages versions
ilcsoft_set_package_version( PACKAGE GEAR                     VERSION "master" )
ilcsoft_set_package_version( PACKAGE LCIO                     VERSION "master" )
ilcsoft_set_package_version( PACKAGE MarlinFastJet            VERSION "master" )
ilcsoft_set_package_version( PACKAGE KalTest                  VERSION "master" )
ilcsoft_set_package_version( PACKAGE KalDet                   VERSION "master" )
ilcsoft_set_package_version( PACKAGE aidaTT                   VERSION "master" )
ilcsoft_set_package_version( PACKAGE DDKalTest                VERSION "master" )
ilcsoft_set_package_version( PACKAGE MarlinTrk                VERSION "master" )
ilcsoft_set_package_version( PACKAGE MarlinTrkProcessors      VERSION "master" )
ilcsoft_set_package_version( PACKAGE Clupatra                 VERSION "master" )
ilcsoft_set_package_version( PACKAGE KiTrack                  VERSION "master" )
ilcsoft_set_package_version( PACKAGE KiTrackMarlin            VERSION "master" )
ilcsoft_set_package_version( PACKAGE ForwardTracking          VERSION "master" )
ilcsoft_set_package_version( PACKAGE ConformalTracking        VERSION "master" )
ilcsoft_set_package_version( PACKAGE LICH                     VERSION "master" )
ilcsoft_set_package_version( PACKAGE GBL                      VERSION "trunk" )
ilcsoft_set_package_version( PACKAGE LCCD                     VERSION "master" )
ilcsoft_set_package_version( PACKAGE RAIDA                    VERSION "master" )
ilcsoft_set_package_version( PACKAGE MarlinUtil               VERSION "master" )
ilcsoft_set_package_version( PACKAGE Marlin                   VERSION "master" )
ilcsoft_set_package_version( PACKAGE MarlinDD4hep             VERSION "master" )
ilcsoft_set_package_version( PACKAGE DDMarlinPandora          VERSION "master" )
ilcsoft_set_package_version( PACKAGE MarlinReco               VERSION "master" )
ilcsoft_set_package_version( PACKAGE FCalClusterer            VERSION "master" )
ilcsoft_set_package_version( PACKAGE ILDPerformance           VERSION "master" )
ilcsoft_set_package_version( PACKAGE ILDConfig                VERSION "master" )
ilcsoft_set_package_version( PACKAGE LCFIVertex               VERSION "master" )
ilcsoft_set_package_version( PACKAGE LCFIPlus                 VERSION "master" )
ilcsoft_set_package_version( PACKAGE MarlinKinfit             VERSION "master" )
ilcsoft_set_package_version( PACKAGE MarlinKinfitProcessors   VERSION "master" )
ilcsoft_set_package_version( PACKAGE PandoraPFANew            VERSION "master" )
ilcsoft_set_package_version( PACKAGE PandoraAnalysis          VERSION "master" )
ilcsoft_set_package_version( PACKAGE CEDViewer                VERSION "master" )
ilcsoft_set_package_version( PACKAGE Overlay                  VERSION "master" )
ilcsoft_set_package_version( PACKAGE PathFinder               VERSION "trunk" )
ilcsoft_set_package_version( PACKAGE MarlinTPC                VERSION "trunk" )
ilcsoft_set_package_version( PACKAGE LCTuple                  VERSION "master" )
ilcsoft_set_package_version( PACKAGE BBQ                      VERSION "trunk" )
ilcsoft_set_package_version( PACKAGE Garlic                   VERSION "master" )
ilcsoft_set_package_version( PACKAGE DD4hep                   VERSION "master" )
ilcsoft_set_package_version( PACKAGE DD4hepExamples           VERSION "master" )
ilcsoft_set_package_version( PACKAGE lcgeo                    VERSION "master" )
ilcsoft_set_package_version( PACKAGE Physsim                  VERSION "master" )
